    %% smoothed ramp to initialise simulation
    I_imposed = I(t);%/(1+exp((-t+dt)));

    %% coupled pde
    pde.op = @(x, ps, pe) ... %, ce) ...
        [diff(sigma.*diff(ps)) - j(ce,cs,pe,ps);...
          k.*diff(pe,2) + kD.*diff(diff(ce)./ce) + j(ce,cs,pe,ps)];%; ...
%          De.*diff(ce,2) + (1-t0).*j(ce,cs,pe,ps)/F/cmax./(1-nn) - ce/dt];
    pde.lbc = @(ps, pe) ... %, ce) ...
        [sigma1*diff(ps)-I_imposed/A1; ...
        diff(pe)]; %; ...
%        diff(ce)];
    pde.rbc = @(ps, pe) ... %, ce) ...
        [sigma2*diff(ps)-I_imposed/A2; ...
        diff(pe)]; %; ...
%        diff(ce)];
    rhs = [0; 0]; %; (-ce/dt)];
    pde.bc=@(x,ps,pe) [pe(0)];


    pde_ce.op = @(ce) De.*diff(ce,2) + (1-t0).*j(ce,cs,pe,ps)/F/cmax./(1-nn) - ce/dt;
    
